ci/cd:
  - .github/**

build:
  - CMakeLists.txt
  - .clang-format
  - .clang-tidy

chore:
  - .gitignore

documentation:
  - LICENSE.md
  - README.md
  - ./*.md

main:
  - main.c

reader:
  - modules/reader/**

argparser:
  - modules/argparser/**

config:
  - modules/config.h